#!/bin/bash

set -euo pipefail

if [ -z "${SPIN_TOOLS_VERSION:-}" ] ; then
	>&2 echo "Not running in a spin docker image, run ./go instead"
	exit 1
fi

USAGE="Usage: gojo [test|test-online]"


if [ "$#" -eq 0 ] ; then
    >&2  echo "No command given"
    >&2  echo ${USAGE}
    exit 1
fi


for arg in "$@"
do
	case "$arg" in
	test|test-offline|offline)
		echo "Running offline tests"
		spin-test test/offline
		;;
	test-online|online-test|online-tests|online)
		echo "Running online tests"
		spin-test test/online
		;;
	help)
	    >&2  echo ${USAGE}
		;;
	*)
	    >&2  echo "Unknown command ${arg}"
	    >&2  echo ${USAGE}
	    exit 1
		;;
	esac
done

