---
stack_instance:

  stack_name: website-stack
  instance_id: staging

  parameters:
    website_name: cloudspin-examples.com
    instance_name: staging
    unique_id: staging123

  platform:
    name: aws
    parameters:
      aws_region: us-east-2
      aws_profile: spintools_aws

  tool: 
    name: terraform
    backend:
      name: local
