name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate_stack_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      -
        name: Install dojo
        run: |
          mkdir -p ./bin
          wget -O ./bin/dojo https://github.com/kudulab/dojo/releases/download/0.11.0/dojo_linux_amd64
          chmod +x ./bin/dojo

      -
        name: Run offline tests
        run: |
          ./bin/dojo "./go test"
