name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install terraform
        run: sudo apt-get -y install terraform

      - name: Run validate
        run: |
          cd src
          terraform init -backend=false
          terraform validate

