name: Offline tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_the_stack_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      -
        name: Install dojo
        run: |
          mkdir -p ./bin
          wget --quiet -O ./bin/dojo https://github.com/kudulab/dojo/releases/download/0.11.0/dojo_linux_amd64
          chmod +x ./bin/dojo
          echo "./bin" >> $GITHUB_PATH
      -
        name: Install docker-compose
        run: |
          wget --quiet -O ./bin/docker-compose https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64
          chmod +x ./bin/docker-compose
          mkdir -p ~/.docker/cli-plugins
          cp ./bin/docker-compose ~/.docker/cli-plugins/
      -
        name: Run offline tests
        run: |
          ./go test
