name: Online tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_the_stack_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      -
        name: Install dojo
        run: |
          mkdir -p ./bin
          wget --quiet -O ./bin/dojo https://github.com/kudulab/dojo/releases/download/0.11.0/dojo_linux_amd64
          chmod +x ./bin/dojo
          echo "./bin" >> $GITHUB_PATH
      -
        name: Run online tests
        run: ./go test-online
        env:
          AWS_SANDBOX_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SANDBOX_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TARGET_INSTANCE_CONFIGURATION_FILE: instances/online-instance.yml
  